apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: external-secrets
  pass_credentials_all: false
  password: ""
  url: https://charts.external-secrets.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: tailscale
  pass_credentials_all: false
  password: ""
  url: https://pkgs.tailscale.com/helmcharts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: longhorn
  pass_credentials_all: false
  password: ""
  url: https://charts.longhorn.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: cloudnative-pg
  pass_credentials_all: false
  password: ""
  url: https://cloudnative-pg.github.io/charts
  username: ""
