---
namespace: ntfy
labels:
  - pairs:
      app: ntfy
    includeSelectors: true
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ntfy
    newName: docker.io/binwiederhier/ntfy
    newTag: "v2.15.0"
configMapGenerator:
  - name: env
    envs:
      - env.sh
