---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: external-secrets
spec:
  repo: https://charts.external-secrets.io
  chart: external-secrets
  version: 1.0.0
  createNamespace: true
  targetNamespace: external-secrets
  set:
    installCRDs: "true"
---
