---
namespace: default
namePrefix: miniflux-
labels:
  - pairs:
      app: miniflux
    includeSelectors: true
resources:
  - app-config.yaml
  - cluster.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjob-refresh.yaml
  - cronjob-cleanup.yaml
images:
  - name: miniflux
    newName: ghcr.io/miniflux/miniflux
    newTag: "2.2.14-distroless"
