- command: "mount --make-rshared /"
- register: make_rshared
  copy:
    dest: /etc/local.d/make_rshared.start
    mode: '744'
    content: |
      #!/bin/sh
      exec mount --make-rshared /
- service:
    name: local
    enabled: true
- community.general.apk:
    name:
      - iproute2-ss
      - open-iscsi
      - nfs-utils
      - rsync
      - '!prometheus-node-exporter'
      - k3s
- service:
    name: iscsid
    enabled: true
